// Content thương mại điện tử — one landing page (COMMERCE_LP_PLAN.md).
import {shop} from './shop.mjs';
import {productBrief, listingCompare, marketPdp, videoShop, storyboard, chatQueue, reasons, calendar} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'content-thuong-mai-dien-tu', channel: 'ecomContent', name: 'Content thương mại điện tử', docName: 'Học viện Shopee và Học viện TikTok Shop',
  metaTitle: 'Content thương mại điện tử: mô tả sản phẩm, ảnh, video, nội dung gian hàng',
  metaDescription: 'Nội dung giúp khách hiểu lợi ích, cách dùng và điểm khác biệt của sản phẩm trên sàn: brief sản phẩm, mô tả theo nhu cầu, ảnh và video chứng minh, kiểm tra thông tin với nguồn doanh nghiệp.',
  sub: 'Nội dung giúp khách <em>hiểu cách dùng và chọn đúng</em>, không chỉ liệt kê tính năng.',
  lead: 'Nội dung nói nhiều tính năng nhưng chưa giúp khách hiểu cách dùng và lựa chọn là lỗi hay gặp. POWAI thu thông số và tài liệu nguồn, viết mô tả theo nhu cầu sử dụng, '
    + 'chọn ảnh hoặc demo chứng minh và kiểm tra giá, công dụng, quyền tài nguyên trước khi đăng.',
  cta: 'Xem bộ nội dung sản phẩm',
  scene: () => ({main: productBrief(), side: videoShop(),
    calls: [['Thông tin gốc', 'Doanh nghiệp xác nhận'], ['Mô tả theo nhu cầu', 'Ai dùng, dùng thế nào'], ['Ảnh & video chứng minh', 'Đúng sản phẩm, được phép']]}),
  intro: {q: 'Content thương mại điện tử là gì?',
    a: 'Là toàn bộ nội dung giúp khách mua trên sàn hoặc website: tên và mô tả sản phẩm, ảnh, video ngắn, nội dung trang gian hàng, câu trả lời mẫu. '
      + 'Khác content mạng xã hội, nội dung này nằm ngay chỗ khách quyết định mua, nên phải đúng thông số, đúng chính sách và theo quy định nội dung của từng sàn.',
    facts: [['Nằm ở', 'Trang sản phẩm, gian hàng, video'], ['Phải đúng', 'Thông số, giá, công dụng, quyền tài nguyên'], ['Đo bằng', 'Câu hỏi lặp lại, hoàn vì hiểu sai']]},
  essentials: {title: 'Sáu điều của nội dung bán được hàng.', lead: 'Theo hướng dẫn mô tả sản phẩm và chính sách nội dung của các sàn.',
    cards: [['file', 'Brief trước khi viết', 'Sản phẩm, ai mua, câu hỏi hay gặp, thông tin gốc, điều không được nói.'],
      ['users', 'Viết theo nhu cầu sử dụng', 'Dùng khi nào, cho ai, khác mẫu khác ở đâu.'],
      ['check', 'Thông tin đối chiếu được', 'Thông số, giá, công dụng khớp tài liệu doanh nghiệp.'],
      ['image', 'Ảnh & video chứng minh', 'Cận cảnh, kích thước thật, cách dùng; do shop làm hoặc được phép dùng.'],
      ['shield', 'Đúng chính sách nội dung', 'Không phóng đại công dụng, không nội dung sàn không cho phép.'],
      ['repeat', 'Dùng lại trên nhiều kênh', 'Một bộ nội dung gốc cho sàn, website, video ngắn.']],
    get: ['POWAI bàn giao', ['Brief cho từng sản phẩm', 'Tên, mô tả, thuộc tính đã duyệt', 'Danh sách ảnh, video cần có', 'Kịch bản video ngắn (theo phạm vi)', 'Bảng kiểm thông tin trước khi đăng']],
    not: ['Tính riêng hoặc cần phối hợp', ['Chụp ảnh, quay dựng video', 'Người sáng tạo nội dung, KOL', 'Quảng cáo nội dung']],
    src: ['shopeeDesc', 'ttTitle', 'ttContent']},
  when: {title: 'Khi khách xem mà vẫn phải hỏi lại, hoặc hiểu sai sản phẩm.', lead: 'Hợp với sản phẩm cần giải thích: mỹ phẩm, đồ gia dụng, quà tặng, sản phẩm nhiều mẫu.',
    journey: [['file', 'Thu thông tin gốc'], ['users', 'Hiểu người mua'], ['page', 'Viết mô tả'], ['image', 'Chọn ảnh, video'], ['check', 'Kiểm tra, đăng']],
    inputs: [['file', 'Thông số, tài liệu sản phẩm'], ['image', 'Ảnh, video sẵn có'], ['chat', 'Câu hỏi của khách'], ['users', 'Người duyệt thông tin']],
    core: 'Brief, viết, kiểm tra',
    outputs: [['file', 'Brief sản phẩm'], ['page', 'Nội dung đã duyệt'], ['video', 'Kịch bản video']],
    fit: ['Khách hỏi lại thông tin cơ bản', 'Hoàn hàng vì hiểu sai công dụng, kích thước', 'Mô tả sao chép từ nhà cung cấp', 'Nhiều sàn, nội dung mỗi nơi một kiểu'],
    notFit: ['Chưa có thông số được xác nhận', 'Muốn nói công dụng chưa chứng minh', 'Dùng ảnh, video không có quyền', 'Chỉ cần nội dung mạng xã hội: xem Social'],
    src: ['shopeeDesc', 'ttTitle']},
  formatsToc: 'Bộ nội dung',
  formats: {eyebrow: 'BỘ NỘI DUNG SẢN PHẨM', title: 'Năm phần nội dung cho một sản phẩm.', lead: 'Chọn một phần để xem viết gì.',
    whereLabel: 'Nằm ở', whatLabel: 'Viết thế nào',
    items: [
      {key: 'brief', label: 'Brief sản phẩm', icon: 'file', stage: () => productBrief(), tag: 'MẪU', where: 'Trước mọi nội dung.', what: 'Ai mua, câu hỏi hay gặp, thông tin gốc, điều không được nói.'},
      {key: 'compare', label: 'Tên & mô tả', icon: 'tag', stage: () => listingCompare(), tag: 'MẪU', where: 'Trang sản phẩm.', what: 'Tên đúng loại; mô tả trả lời câu hỏi, không liệt kê suông.',
        more: [['Theo', 'Hướng dẫn mô tả sản phẩm đúng chuẩn của Học viện Shopee.']]},
      {key: 'pdp', label: 'Ảnh từng mẫu', icon: 'image', stage: () => marketPdp(), tag: 'PHÍA KHÁCH', where: 'Ảnh bìa, ảnh phân loại.', what: 'Ảnh thật, cận chi tiết, mỗi mẫu một ảnh.'},
      {key: 'video', label: 'Video ngắn', icon: 'video', stage: () => videoShop(), tag: 'PHÍA KHÁCH', where: 'Trang sản phẩm, video gắn sản phẩm.', what: 'Cách dùng, kích thước thật, đúng mẫu đang bán.'},
      {key: 'story', label: 'Kịch bản video', icon: 'list', stage: () => storyboard(2), tag: 'MẪU', where: 'Trước khi quay.', what: 'Mở đầu, demo, bằng chứng, hành động.'}
    ],
    src: ['shopeeDesc', 'ttTitle', 'ttContent']},
  prep: {title: 'Thông tin gốc do doanh nghiệp xác nhận.', lead: 'Nội dung sai thông số là nguồn hoàn hàng và khiếu nại.',
    principle: 'Mọi thông tin về sản phẩm đối chiếu được với nguồn doanh nghiệp cung cấp.',
    boardLabel: 'BRIEF SẢN PHẨM', boards: [() => productBrief()],
    tiles: [['file', 'Thông số', 'Được xác nhận'], ['image', 'Ảnh, video', 'Quyền sử dụng'], ['chat', 'Câu hỏi khách', 'Từ tin nhắn, đánh giá'], ['users', 'Người duyệt', 'Thông tin, công dụng']],
    assets: [['Chữ', 'Thông số, cách dùng', 'Doanh nghiệp xác nhận.'], ['Ảnh', 'Ảnh sản phẩm', 'Quyền sử dụng.'], ['Video', 'Cảnh quay sẵn có', 'Quyền nhạc, hình.'], ['Phản hồi', 'Câu hỏi, đánh giá', 'Gần nhất.']],
    specs: [['Mô tả', 'Mô tả đúng chuẩn', 'Hướng dẫn của Học viện Shopee.'], ['Tiêu đề, ảnh, video', 'Đầy đủ, chính xác, ngắn gọn', 'Học viện TikTok Shop.'], ['Chính sách', 'Chính sách nội dung', 'Nội dung chân thực, không phóng đại.']],
    src: ['shopeeDesc', 'ttTitle', 'ttContent']},
  goals: {title: 'Nội dung có giúp khách mua đúng không.', lead: 'Nhóm đầu là phía khách, nhóm sau là dữ liệu shop.',
    items: [
      {key: 'chat', group: 'Phía khách', groupColor: '#d4b3ff', label: 'Câu hỏi lặp lại', icon: 'chat', stage: () => chatQueue(0), facts: [['Đọc', 'Câu nào khách còn hỏi sau khi đọc trang.'], ['Sửa', 'Thêm vào mô tả hoặc ảnh.']]},
      {key: 'video', group: 'Phía khách', groupColor: '#d4b3ff', label: 'Video đúng mẫu', icon: 'video', stage: () => videoShop(), facts: [['Kiểm', 'Mẫu trong video đúng mẫu đang bán.'], ['Tránh', 'Video mẫu cũ, mẫu đã ngừng.']]},
      {key: 'reasons', group: 'Dữ liệu shop', groupColor: '#88e4ff', label: 'Hoàn vì hiểu sai', icon: 'chart', stage: () => reasons(3), stageTag: 'SỐ MẪU', facts: [['Đọc', 'Hoàn vì sai kích thước, công dụng.'], ['Sửa', 'Nói rõ trong nội dung.']]},
      {key: 'cal', group: 'Dữ liệu shop', groupColor: '#88e4ff', label: 'Lịch nội dung', icon: 'calendar', stage: () => calendar(2), stageTag: 'MẪU', facts: [['Dùng', 'Lịch video, bài cho sản phẩm chủ lực.'], ['Người duyệt', 'Thông tin trước khi đăng.']]}
    ],
    src: ['shopeeDesc', 'ttContent']},
  measure: {title: 'Đo nội dung bằng câu hỏi và hoàn hàng.', lead: 'Bấm từng tầng. Số là một sản phẩm giả định trong một tháng để minh họa cách đọc.', sample: 'Một sản phẩm giả định trong một tháng, chỉ để minh họa cách đọc.',
    tiers: [['view', 'Lượt xem', '3.000', [['Lượt xem trang', '3.000', 'Trong sàn.'], ['Xem video', '1.100', 'Trên trang sản phẩm.']]],
      ['ask', 'Câu hỏi', '60', [['Câu hỏi trước mua', '60', 'Tin nhắn.'], ['Câu lặp lại', '22', 'Nội dung còn thiếu.']]],
      ['done', 'Đơn đúng', '118', [['Đơn hoàn tất', '118', 'Sau hoàn.'], ['Hoàn vì hiểu sai', '3', 'Kích thước, công dụng.']]]],
    tips: {ask: 'Câu hỏi lặp lại nhiều: bổ sung vào mô tả, ảnh chú thích.', done: 'Hoàn vì hiểu sai: kiểm nội dung có nói rõ kích thước, cách dùng.'},
    note: {label: 'KHÔNG ĐO BẰNG SỐ CHỮ', ic: 'file', text: 'Mô tả dài không phải mô tả tốt; đo bằng câu hỏi giảm và hoàn hàng vì hiểu sai giảm.'},
    src: ['shopeeDesc']},
  step2: 'Brief, viết tên và mô tả, chọn ảnh, kịch bản video; kiểm thông tin trước khi đăng.',
  rollout: {title: 'Năm bước từ thông tin gốc tới nội dung đăng.',
    checks: ['Thông số được xác nhận', 'Brief cho từng sản phẩm', 'Tên đúng loại sản phẩm', 'Mô tả trả lời câu hỏi hay gặp',
      'Ảnh từng mẫu, được phép dùng', 'Video đúng mẫu đang bán', 'Không phóng đại công dụng', 'Người duyệt trước khi đăng'],
    src: ['shopeeDesc', 'ttContent']},
  faq: [['Có viết nội dung cho nhiều sàn không?', 'Có; viết một bộ gốc rồi điều chỉnh theo quy định từng sàn.'],
    ['Có dùng AI viết mô tả không?', 'Có thể hỗ trợ bản nháp; mọi thông số, công dụng phải đối chiếu với nguồn doanh nghiệp.'],
    ['Nội dung cho sản phẩm cần giấy phép thì sao?', 'Chỉ nêu công dụng trong giấy tờ được cấp; ngành hàng đặc thù cần doanh nghiệp duyệt kỹ.'],
    ['Có quay video không?', 'Có thể tách phạm vi riêng; trang này tập trung vào kịch bản và nội dung chữ.']],
  faqSrc: ['shopeeDesc', 'ttContent'],
  recap: {title: 'Ba việc cho nội dung sản phẩm.', items: [['Brief trước', 'Thông tin gốc đã xác nhận.', '#dinh-dang', 'file'],
    ['Viết theo nhu cầu', 'Không liệt kê suông.', '#dinh-dang', 'page'], ['Ảnh, video chứng minh', 'Đúng mẫu.', '#dinh-dang', 'image']]},
  sisters: sisters('toi-uu-san-pham', 'tiktok-shop', 'shopee')
});
