// Quảng cáo sàn — one landing page (COMMERCE_LP_PLAN.md). Search ads facts
// from Học viện Shopee; other marketplaces follow their own tools.
import {shop} from './shop.mjs';
import {adsReport, keywordBids, marketSearch, marketPdp, skuTable, reasons, netRevenue} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'quang-cao-san', channel: 'ecomAds', name: 'Quảng cáo sàn', docName: 'Học viện Shopee',
  metaTitle: 'Quảng cáo sàn thương mại điện tử: chọn SKU, từ khóa, giá thầu, đối soát đơn hoàn tất',
  metaDescription: 'Quảng cáo trong sàn theo sản phẩm, ngân sách và chất lượng đơn: chọn SKU có nguồn hàng ổn định, từ khóa và giá thầu, giới hạn thử theo sản phẩm, đối soát đơn hoàn tất và hủy.',
  sub: 'Biết <em>sản phẩm nào</em> tạo đơn có giá trị trước khi tăng ngân sách.',
  lead: 'Chi tiền quảng cáo nhưng chưa biết sản phẩm nào tạo đơn có giá trị là tình huống hay gặp. POWAI chọn SKU có nguồn hàng ổn định, kiểm tra công cụ nhắm mục tiêu của sàn, '
    + 'đặt giới hạn thử theo sản phẩm và đối soát đơn hoàn tất, hủy trước khi tăng ngân sách.',
  cta: 'Xem cách chạy quảng cáo sàn',
  scene: () => ({main: adsReport(1), side: marketSearch({ad: true}),
    calls: [['Chọn SKU', 'Có hàng, có lãi'], ['Từ khóa & giá thầu', 'Đúng nhu cầu mua'], ['Đối soát đơn hoàn tất', 'Không chỉ đơn sàn báo']]}),
  intro: {q: 'Quảng cáo sàn là gì?',
    a: 'Là quảng cáo trả phí ngay trong sàn thương mại điện tử để sản phẩm hoặc shop xuất hiện ở vị trí nổi bật: trong kết quả tìm kiếm, trang khám phá, gợi ý sản phẩm. '
      + 'Mỗi sàn có công cụ riêng; ví dụ Shopee có Quảng cáo Tìm kiếm (sản phẩm, shop) và Quảng cáo Khám phá, đặt giá thầu theo từ khóa hoặc để hệ thống tự chọn.',
    facts: [['Xuất hiện ở', 'Tìm kiếm, khám phá trong sàn'], ['Trả tiền theo', 'Cơ chế của từng sàn'], ['Đo bằng', 'Đơn hoàn tất, tiền thực nhận']]},
  essentials: {title: 'Sáu điều trước khi tăng ngân sách quảng cáo sàn.', lead: 'Quảng cáo khuếch đại trang sản phẩm; trang yếu thì quảng cáo tốn tiền.',
    cards: [['table', 'Chọn SKU đúng', 'Sản phẩm có nguồn hàng ổn định, trang sản phẩm tốt, còn lãi sau phí.'],
      ['search', 'Quảng cáo tìm kiếm', 'Đặt giá thầu theo từ khóa người mua hay dùng; hoặc để hệ thống tự chọn từ khóa liên quan.'],
      ['eye', 'Quảng cáo khám phá & shop', 'Hiển thị ở gợi ý, trang khám phá; quảng cáo shop đưa khách tới gian hàng.'],
      ['wallet', 'Giới hạn thử theo sản phẩm', 'Ngân sách nhỏ cho từng SKU, đọc sau một khoảng đủ dài.'],
      ['receipt', 'Đối soát đơn hoàn tất', 'Đơn sàn báo chưa trừ hủy, hoàn; đọc đơn hoàn tất.'],
      ['chart', 'Tiền thực nhận', 'Doanh số trừ phí sàn, mã giảm giá, chi phí quảng cáo.']],
    get: ['POWAI bàn giao', ['Danh sách SKU nên quảng cáo', 'Cấu hình chiến dịch theo sàn', 'Bảng từ khóa, giá thầu (nếu dùng)', 'Báo cáo tuần theo sản phẩm', 'Đối soát đơn hoàn tất và tiền thực nhận']],
    not: ['Tính riêng hoặc cần phối hợp', ['Ngân sách quảng cáo trả cho sàn', 'Sửa trang sản phẩm: xem Tối ưu sản phẩm', 'Cam kết doanh số, thứ hạng']],
    src: ['shopeeSearchAds', 'shopeeShopAds', 'shopeeFees']},
  when: {title: 'Khi trang sản phẩm đã ổn và muốn thêm người xem.', lead: 'Quảng cáo sàn hiệu quả nhất khi sản phẩm đã có trang tốt và đánh giá.',
    journey: [['table', 'Chọn SKU'], ['search', 'Chọn từ khóa, vị trí'], ['wallet', 'Đặt ngân sách thử'], ['eye', 'Theo dõi hiển thị, lượt bấm'], ['receipt', 'Đối soát đơn hoàn tất']],
    inputs: [['table', 'Danh sách SKU, giá vốn'], ['tag', 'Trang sản phẩm đã tối ưu'], ['wallet', 'Ngân sách thử'], ['store', 'Quyền quảng cáo trong Kênh Người Bán']],
    core: 'Chọn sản phẩm, thử, đối soát',
    outputs: [['list', 'SKU giữ / dừng'], ['chart', 'Báo cáo theo sản phẩm'], ['wallet', 'Tiền thực nhận']],
    fit: ['Đã có sản phẩm bán được tự nhiên', 'Muốn đẩy sản phẩm mới có trang tốt', 'Chi quảng cáo mà không biết lãi lỗ', 'Nhiều SKU, cần chọn nơi đặt tiền'],
    notFit: ['Trang sản phẩm chưa rõ, chưa có đánh giá', 'Hàng không đủ để giao khi đơn tăng', 'Không biết giá vốn', 'Muốn quảng cáo mọi sản phẩm cùng lúc'],
    src: ['shopeeSearchAds', 'shopeeShopAds']},
  formatsToc: 'Cách chạy',
  formats: {eyebrow: 'CÁCH CHẠY', title: 'Năm bước của một vòng quảng cáo sàn.', lead: 'Chọn một bước để xem làm gì.',
    whereLabel: 'Làm gì', whatLabel: 'Kiểm tra',
    items: [
      {key: 'sku', label: 'Chọn SKU', icon: 'table', stage: () => skuTable(1), tag: 'KÊNH NGƯỜI BÁN', where: 'Sản phẩm có hàng, có lãi, trang tốt.', what: 'Loại SKU sắp hết hàng hoặc trang còn lỗi.'},
      {key: 'search', label: 'Vị trí tìm kiếm', icon: 'search', stage: () => marketSearch({ad: true}), tag: 'PHÍA KHÁCH', where: 'Sản phẩm hiện ở kết quả tìm kiếm có nhãn tài trợ.', what: 'Ảnh bìa, tên, giá cạnh tranh với kết quả bên cạnh.',
        more: [['Theo', 'Học viện Shopee: quảng cáo sản phẩm ở vị trí Tìm kiếm.']]},
      {key: 'bids', label: 'Từ khóa & giá thầu', icon: 'sliders', stage: () => keywordBids(1), tag: 'KÊNH NGƯỜI BÁN', where: 'Từ khóa người mua hay dùng.', what: 'Ưu tiên từ khóa đúng nhu cầu mua; theo dõi từ khóa tốn tiền không ra đơn.'},
      {key: 'report', label: 'Báo cáo theo sản phẩm', icon: 'chart', stage: () => adsReport(1), tag: 'SỐ MẪU', where: 'Chi tiêu, đơn sàn báo, đơn hoàn tất.', what: 'Giữ, xem lại hoặc dừng từng SKU.'},
      {key: 'money', label: 'Tiền thực nhận', icon: 'wallet', stage: () => netRevenue(), where: 'Sau phí, mã giảm giá, quảng cáo, hoàn hủy.', what: 'Quyết định tăng ngân sách theo lãi, không theo doanh số.'}
    ],
    note: {label: 'CHỐT SÀN TRƯỚC', ic: 'store', text: 'Mỗi sàn có loại chiến dịch và cách nhắm riêng; chọn sàn trước khi chọn loại chiến dịch, không áp một cách chạy cho mọi sàn.'},
    src: ['shopeeSearchAds', 'shopeeShopAds', 'shopeeFees']},
  prep: {title: 'Biết giá vốn và phí trước khi đặt giá thầu.', lead: 'Không biết lãi trên mỗi đơn thì không biết quảng cáo đang lời hay lỗ.',
    principle: 'Mỗi SKU có trần chi phí quảng cáo tính từ giá bán, giá vốn và phí sàn.',
    boardLabel: 'TỪ DOANH SỐ TỚI TIỀN THỰC NHẬN', boards: [() => netRevenue()],
    tiles: [['table', 'Giá vốn từng SKU', 'Doanh nghiệp cung cấp'], ['wallet', 'Phí sàn', 'Theo chính sách hiện hành'], ['tag', 'Trang sản phẩm', 'Đã tối ưu'], ['box', 'Tồn kho', 'Đủ khi đơn tăng']],
    assets: [['Dữ liệu', 'Giá vốn, giá bán', 'Theo SKU.'], ['Phí', 'Phí sàn, thanh toán', 'Trong Kênh Người Bán.'], ['Trang', 'Sản phẩm sẽ quảng cáo', 'Đã rà soát.'], ['Kho', 'Tồn kho dự kiến', 'Cho thời gian chạy.']],
    specs: [['Quảng cáo Tìm kiếm', 'Giá thầu theo từ khóa', 'Hoặc để hệ thống tự chọn từ khóa liên quan.'], ['Quảng cáo Shop', 'Đưa khách tới gian hàng', 'Theo hướng dẫn Quảng cáo Shop.'],
      ['Phí', 'Các loại phí bán hàng', 'Xem trong Học viện Shopee.']],
    src: ['shopeeSearchAds', 'shopeeShopAds', 'shopeeFees']},
  goals: {title: 'Những lúc quảng cáo tốn tiền mà không lãi.', lead: 'Nhóm đầu là phía khách, nhóm sau là dữ liệu shop.',
    items: [
      {key: 'out', group: 'Phía khách', groupColor: '#ffd08a', label: 'Quảng cáo sản phẩm sắp hết', icon: 'tag', stage: () => marketPdp({state: 'out'}), facts: [['Hậu quả', 'Trả tiền cho lượt bấm rồi khách không mua được.'], ['Sửa', 'Dừng quảng cáo SKU sắp hết.']]},
      {key: 'bids', group: 'Phía khách', groupColor: '#ffd08a', label: 'Từ khóa quá rộng', icon: 'search', stage: () => keywordBids(0), facts: [['Dấu hiệu', 'Nhiều lượt bấm, ít đơn.'], ['Sửa', 'Ưu tiên từ khóa đúng nhu cầu mua.']]},
      {key: 'cancel', group: 'Dữ liệu shop', groupColor: '#88e4ff', label: 'Đơn sàn báo nhiều, hoàn tất ít', icon: 'receipt', stage: () => reasons(0), stageTag: 'SỐ MẪU', facts: [['Đọc', 'Hủy, hoàn theo lý do.'], ['Sửa', 'Xử lý nguyên nhân trước khi tăng tiền.']]},
      {key: 'report', group: 'Dữ liệu shop', groupColor: '#88e4ff', label: 'Chọn SKU giữ hay dừng', icon: 'chart', stage: () => adsReport(3), stageTag: 'SỐ MẪU', facts: [['Giữ', 'Đơn hoàn tất tốt so với chi tiêu.'], ['Dừng', 'Chi nhiều, hoàn tất ít.']]}
    ],
    src: ['shopeeFailRate', 'shopeeFees']},
  measure: {title: 'Đọc từ chi tiêu tới đơn hoàn tất.', lead: 'Bấm từng tầng. Số là một tuần giả định để minh họa cách đọc.', sample: 'Một tuần giả định, chỉ để minh họa cách đọc.',
    tiers: [['spend', 'Chi tiêu', '4.200', [['Chi tiêu (nghìn đồng)', '4.200', 'Mọi SKU.'], ['Lượt bấm', '2.600', 'Từ quảng cáo.']]],
      ['order', 'Đơn sàn báo', '94', [['Đơn từ quảng cáo', '94', 'Sàn ghi nhận.'], ['Hủy, hoàn', '13', 'Theo lý do.']]],
      ['done', 'Hoàn tất', '81', [['Đơn hoàn tất', '81', 'Sau hủy, hoàn.'], ['Tiền thực nhận', 'mẫu', 'Sau phí, mã, quảng cáo.']]]],
    tips: {order: 'Nhiều lượt bấm, ít đơn: xem trang sản phẩm và từ khóa.', done: 'Hoàn tất thấp hơn nhiều so với đơn sàn báo: kiểm tra lý do hủy.'},
    note: {label: 'KHÔNG CHỈ ĐỌC SỐ SÀN BÁO', ic: 'alert', tone: 'warn', text: 'Số đơn và doanh thu từ quảng cáo trong báo cáo sàn chưa trừ hủy, hoàn và phí; quyết định theo đơn hoàn tất và tiền thực nhận.'},
    src: ['shopeeSearchAds', 'shopeeFees']},
  step2: 'Chọn SKU, loại chiến dịch theo sàn, từ khóa và giá thầu, giới hạn ngân sách thử.',
  rollout: {title: 'Năm bước một vòng quảng cáo sàn.',
    checks: ['Biết giá vốn từng SKU', 'Trang sản phẩm đã tối ưu', 'Tồn kho đủ cho thời gian chạy', 'Ngân sách thử theo sản phẩm',
      'Từ khóa đúng nhu cầu mua', 'Theo dõi từ khóa tốn tiền', 'Đối soát đơn hoàn tất', 'Tính tiền thực nhận trước khi tăng'],
    src: ['shopeeSearchAds', 'shopeeFees']},
  faq: [['Có chạy quảng cáo trên TikTok Shop không?', 'Có theo công cụ của TikTok; cách chọn sản phẩm và đối soát giống nhau, cách thiết lập khác.'],
    ['Nên để hệ thống tự chọn từ khóa không?', 'Hợp khi mới bắt đầu hoặc ít thời gian; theo dõi và loại từ khóa không phù hợp.'],
    ['Ngân sách bao nhiêu là đủ?', 'Tùy sản phẩm, giá thầu và lãi mỗi đơn; bắt đầu nhỏ theo từng SKU rồi tăng khi có lãi.'],
    ['Phí quảng cáo có gồm trong phí dịch vụ không?', 'Không. Ngân sách trả cho sàn tách riêng với phí dịch vụ POWAI.']],
  faqSrc: ['shopeeSearchAds', 'shopeeFees'],
  recap: {title: 'Ba việc trước khi tăng ngân sách.', items: [['Chọn đúng SKU', 'Có hàng, có lãi.', '#dinh-dang', 'table'],
    ['Đối soát hoàn tất', 'Không chỉ số sàn báo.', '#do-luong', 'receipt'], ['Tính tiền thực nhận', 'Sau mọi phí.', '#chuan-bi', 'wallet']]},
  sisters: sisters('toi-uu-san-pham', 'shopee', 'van-hanh-gian-hang')
});
