// Shopee — one landing page (COMMERCE_LP_PLAN.md). Facts from Học viện Shopee.
import {shop} from './shop.mjs';
import {marketPdp, marketSearch, skuTable, orderBoard, chatQueue, reasons, netRevenue, listingCompare, keywordBids, shopSetup} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'shopee', channel: 'ecomShopee', name: 'Shopee', docName: 'Học viện Shopee',
  metaTitle: 'Dịch vụ gian hàng Shopee: danh mục, biến thể, tồn kho, xử lý đơn, quảng cáo',
  metaDescription: 'Rà soát và vận hành gian hàng Shopee: tổ chức danh mục theo cách khách tìm, ảnh và biến thể đúng từng mẫu, bảng SKU khớp tồn kho, quy trình xử lý đơn và quảng cáo trong sàn.',
  sub: 'Khách chọn <em>đúng mẫu</em>, kho giao <em>đúng hàng</em>.',
  lead: 'Gian hàng có sản phẩm nhưng khách khó chọn đúng mẫu và quy trình xử lý đơn chưa rõ là tình huống hay gặp. POWAI rà gian hàng Shopee từ danh mục, ảnh, biến thể tới bảng SKU, '
    + 'tồn kho và người xác nhận, đóng gói, bàn giao từng đơn.',
  cta: 'Xem các phần của gian hàng',
  scene: () => ({main: skuTable(2), side: marketPdp(),
    calls: [['Danh mục & tìm kiếm', 'Theo cách khách tìm'], ['Biến thể & tồn kho', 'Mỗi mẫu một ảnh, một SKU'], ['Xử lý đơn', 'Có người phụ trách']]}),
  intro: {q: 'Dịch vụ gian hàng Shopee gồm gì?',
    a: 'Là thiết lập, chuẩn hóa và vận hành gian hàng của doanh nghiệp trên Shopee qua Kênh Người Bán: danh mục, trang sản phẩm, phân loại hàng (biến thể), tồn kho, xử lý đơn, '
      + 'tin nhắn và quảng cáo trong sàn. Mục tiêu là khách chọn đúng, đơn đi đúng và số liệu đối soát được.',
    facts: [['Làm trên', 'Kênh Người Bán Shopee'], ['Trọng tâm', 'Sản phẩm, biến thể, đơn hàng'], ['Đo bằng', 'Đơn hoàn tất, tỷ lệ hoàn hủy, tiền thực nhận']]},
  essentials: {title: 'Sáu điều quyết định một gian hàng Shopee chạy tốt.', lead: 'Theo hướng dẫn trong Học viện Shopee và kinh nghiệm vận hành.',
    cards: [['layers', 'Danh mục của shop', 'Sắp sản phẩm theo cách khách tìm: theo nhu cầu, dịp, khoảng giá.'],
      ['image', 'Hình ảnh đúng chuẩn', 'Ảnh do shop làm hoặc được phép dùng; mỗi mẫu có ảnh phân biệt; theo quy định kích thước của Shopee.'],
      ['tag', 'Phân loại hàng chính xác', 'Mỗi biến thể (màu, cỡ, mùi) có giá, tồn kho và ảnh riêng.'],
      ['file', 'Mô tả đúng chuẩn', 'Thông số, cách dùng, chính sách; không dùng từ khóa không liên quan.'],
      ['receipt', 'Xử lý đơn đúng hạn', 'Xác nhận, đóng gói, bàn giao trong thời hạn; tỷ lệ đơn không thành công ảnh hưởng tới shop.'],
      ['wallet', 'Hiểu các loại phí', 'Phí sàn, thanh toán, chương trình theo chính sách hiện hành; tính tiền thực nhận.']],
    get: ['POWAI bàn giao', ['Báo cáo rà soát gian hàng', 'Bảng SKU, biến thể, tồn kho chuẩn hóa', 'Trang sản phẩm đã sửa (theo phạm vi)', 'Quy trình xử lý đơn và tin nhắn', 'Báo cáo đối soát tháng']],
    not: ['Tính riêng hoặc cần phối hợp', ['Phí sàn, phí chương trình, ngân sách quảng cáo', 'Chụp ảnh, quay video sản phẩm', 'Kho, đóng gói, vận chuyển thực tế']],
    src: ['shopeeCategory', 'shopeeImages', 'shopeeVariants', 'shopeeFailRate']},
  when: {title: 'Khi gian hàng có lượt xem mà khách khó chọn, hoặc đơn hay sai.',
    lead: 'Hợp với doanh nghiệp đang bán hoặc sắp bán trên Shopee, có nhiều mẫu, nhiều biến thể.',
    journey: [['search', 'Khách tìm sản phẩm'], ['list', 'Xem danh sách, lọc'], ['tag', 'Chọn biến thể'], ['cart', 'Đặt hàng'], ['box', 'Shop xác nhận, đóng gói, giao']],
    inputs: [['table', 'Danh sách SKU, giá, tồn'], ['image', 'Ảnh sản phẩm được phép dùng'], ['users', 'Người xử lý đơn'], ['store', 'Quyền Kênh Người Bán']],
    core: 'Rà soát, chuẩn hóa, vận hành',
    outputs: [['table', 'Bảng SKU khớp tồn'], ['tag', 'Trang sản phẩm rõ'], ['receipt', 'Quy trình đơn']],
    fit: ['Khách hỏi lại thông tin đã có', 'Hay giao nhầm màu, nhầm cỡ', 'Đơn và tin nhắn bị bỏ sót', 'Chuẩn bị chạy quảng cáo trong sàn'],
    notFit: ['Chưa có sản phẩm, nguồn hàng ổn định', 'Muốn bán hàng không rõ nguồn gốc, không được phép', 'Không có người xử lý đơn', 'Chỉ muốn tăng lượt bán ảo'],
    src: ['shopeeStart', 'shopeeEdu']},
  formatsToc: 'Các phần gian hàng',
  formats: {eyebrow: 'CÁC PHẦN CỦA GIAN HÀNG', title: 'Năm màn hình POWAI rà soát.', lead: 'Hai màn hình phía khách, ba màn hình trong Kênh Người Bán.',
    whereLabel: 'Kiểm tra', whatLabel: 'Sửa thế nào',
    items: [
      {key: 'search', label: 'Kết quả tìm kiếm', icon: 'search', stage: () => marketSearch({hot: 0}), tag: 'PHÍA KHÁCH',
        where: 'Ảnh bìa, tên, giá có nổi bật và đúng không.', what: 'Ảnh bìa rõ sản phẩm; tên nói đúng loại, dung tích, mùi.'},
      {key: 'pdp', label: 'Trang sản phẩm', icon: 'tag', stage: () => marketPdp(), tag: 'PHÍA KHÁCH',
        where: 'Biến thể, giá, tồn, mô tả, đánh giá.', what: 'Mỗi phân loại có ảnh và giá riêng; mô tả đủ thông số, cách dùng.',
        more: [['Theo', 'Hướng dẫn phân loại hàng và mô tả sản phẩm của Học viện Shopee.']]},
      {key: 'sku', label: 'Bảng SKU & tồn kho', icon: 'table', stage: () => skuTable(2), tag: 'KÊNH NGƯỜI BÁN',
        where: 'Mã, biến thể, giá, tồn, ảnh.', what: 'Một SKU cho mỗi biến thể; ảnh không dùng chung; tồn khớp kho thật.'},
      {key: 'orders', label: 'Xử lý đơn', icon: 'receipt', stage: () => orderBoard(1), tag: 'KÊNH NGƯỜI BÁN',
        where: 'Đơn chờ xác nhận, đóng gói, bàn giao.', what: 'Người phụ trách từng bước; đơn thiếu hàng có cách xử lý.'},
      {key: 'chat', label: 'Tin nhắn khách', icon: 'chat', stage: () => chatQueue(2), tag: 'PHÍA SHOP',
        where: 'Câu hỏi trước và sau mua.', what: 'Phân người trực, câu trả lời mẫu, tin chưa có người nhận nổi lên đầu.'}
    ],
    src: ['shopeeVariants', 'shopeeDesc', 'shopeeOrders']},
  prep: {title: 'Dữ liệu hàng hóa sạch trước khi sửa trang.', lead: 'Sai tồn kho hay sai biến thể bắt nguồn từ bảng dữ liệu, không phải từ giao diện.',
    principle: 'Một bảng SKU là nguồn đúng duy nhất: gian hàng, kho và kế toán dùng cùng mã.',
    boardLabel: 'BẢNG SKU', boards: [() => skuTable(2)],
    tiles: [['table', 'Bảng SKU', 'Mã, biến thể, giá, tồn'], ['image', 'Ảnh từng mẫu', 'Được phép dùng'], ['users', 'Người xử lý đơn', 'Theo ca'], ['store', 'Quyền Kênh Người Bán', 'Tài khoản phụ']],
    assets: [['Dữ liệu', 'Bảng SKU', 'Người cập nhật từng trường.'], ['Ảnh', 'Ảnh sản phẩm', 'Mỗi biến thể một ảnh.'], ['Chữ', 'Thông số, chính sách', 'Doanh nghiệp duyệt.'], ['Hệ thống', 'Tài khoản', 'Quyền theo vai trò.']],
    specs: [['Ảnh', 'Theo quy định của Shopee', 'Tỷ lệ, kích thước, dung lượng xem trong Học viện Shopee.'],
      ['Phân loại hàng', 'Mỗi biến thể một giá, một tồn', 'Hướng dẫn thiết lập phân loại hàng.'],
      ['Phí', 'Theo chính sách hiện hành', 'Các loại phí bán hàng xem trong Học viện Shopee.']],
    src: ['shopeeImages', 'shopeeVariants', 'shopeeFees']},
  goals: {title: 'Thử những lúc đơn đi sai.', lead: 'Nhóm đầu là phía khách, nhóm sau là phía vận hành.',
    items: [
      {key: 'out', group: 'Phía khách', groupColor: '#ff9f80', label: 'Biến thể hết hàng', icon: 'tag', stage: () => marketPdp({state: 'out'}),
        facts: [['Cần có', 'Biến thể hết hiện rõ, không bán âm kho.'], ['Thử', 'Chọn mẫu hết, xem thông báo.']]},
      {key: 'compare', group: 'Phía khách', groupColor: '#ff9f80', label: 'Khách chọn nhầm mẫu', icon: 'image', stage: () => listingCompare(),
        facts: [['Nguyên nhân', 'Nhiều mẫu dùng chung một ảnh.'], ['Sửa', 'Mỗi phân loại một ảnh, tên rõ.']]},
      {key: 'short', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Thiếu hàng khi đóng gói', icon: 'box', stage: () => orderBoard(1), stageTag: 'KÊNH NGƯỜI BÁN',
        facts: [['Cần có', 'Người xác nhận tồn trước khi nhận đơn.'], ['Xử lý', 'Liên hệ khách, đổi mẫu hoặc hủy theo quy định.']]},
      {key: 'reasons', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Hoàn, hủy theo lý do', icon: 'chart', stage: () => reasons(1), stageTag: 'SỐ MẪU',
        facts: [['Đọc', 'Tách lỗi shop với khách đổi ý.'], ['Lưu ý', 'Tỷ lệ đơn không thành công ảnh hưởng tới shop.']]},
      {key: 'money', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Tiền thực nhận', icon: 'wallet', stage: () => netRevenue(),
        facts: [['Đọc', 'Doanh số trừ phí, mã giảm giá, quảng cáo, hoàn hủy.'], ['Vì sao', 'Doanh số hiển thị không phải lợi nhuận.']]}
    ],
    src: ['shopeeFailRate', 'shopeeFees']},
  measure: {title: 'Đọc từ lượt xem tới đơn hoàn tất.', lead: 'Bấm từng tầng. Số là một tháng giả định để minh họa cách đọc.',
    tiers: [['view', 'Lượt xem', '12.000', [['Lượt xem sản phẩm', '12.000', 'Trong sàn.'], ['Thêm giỏ', '1.100', 'Theo sản phẩm.']]],
      ['order', 'Đơn đặt', '420', [['Đơn đặt', '420', 'Trước hủy.'], ['Hủy trước giao', '31', 'Theo lý do.']]],
      ['done', 'Hoàn tất', '362', [['Đơn hoàn tất', '362', 'Sau giao, hoàn.'], ['Tiền thực nhận', 'mẫu', 'Sau phí, mã, quảng cáo.']]]],
    tips: {order: 'Nhiều hủy trước giao: kiểm tra tồn kho và thời gian xác nhận đơn.', done: 'Hoàn nhiều ở một sản phẩm: xem lại ảnh, mô tả, biến thể.'},
    note: {label: 'ĐỌC TRONG KÊNH NGƯỜI BÁN', ic: 'chart', text: 'Số liệu thật lấy từ mục Dữ liệu và Tài chính của Kênh Người Bán; POWAI đối chiếu với bảng SKU và kho.'},
    src: ['shopeeFailRate', 'shopeeFees']},
  step2: 'Danh mục, ảnh, tên, phân loại hàng, mô tả theo hướng dẫn Shopee.',
  rollout: {title: 'Năm bước từ bảng SKU tới gian hàng chạy ổn.',
    checks: ['Mỗi biến thể một SKU', 'Ảnh không dùng chung giữa mẫu', 'Tồn kho khớp kho thật', 'Danh mục shop theo cách khách tìm',
      'Người xác nhận đơn theo ca', 'Câu trả lời mẫu cho tin nhắn', 'Thử một đơn mẫu đầu cuối', 'Đối soát tiền thực nhận'],
    src: ['shopeeOrders', 'shopeeVariants']},
  faq: [['Có cam kết tăng doanh số trên Shopee không?', 'Không. POWAI sửa những gì cản khách mua và làm sai đơn; kết quả phụ thuộc sản phẩm, giá, ngành hàng.'],
    ['Có chạy quảng cáo Shopee không?', 'Có, xem trang Quảng cáo sàn; nên chạy sau khi trang sản phẩm và tồn kho đã ổn.'],
    ['Cần giao quyền tài khoản thế nào?', 'Dùng tài khoản phụ hoặc phân quyền theo vai trò; chủ gian hàng giữ tài khoản chính.'],
    ['Bán cả Shopee và TikTok Shop được không?', 'Được; nên dùng chung bảng SKU để tồn kho không lệch giữa các kênh.']],
  faqSrc: ['shopeeEdu', 'shopeeFees'],
  recap: {title: 'Ba việc cho gian hàng Shopee.', items: [['Bảng SKU đúng', 'Một mã mỗi biến thể.', '#chuan-bi', 'table'],
    ['Trang sản phẩm rõ', 'Ảnh, tên, phân loại.', '#dinh-dang', 'tag'], ['Đơn có người nhận', 'Xác nhận, đóng gói, giao.', '#muc-tieu', 'receipt']]},
  sisters: sisters('toi-uu-san-pham', 'van-hanh-gian-hang', 'quang-cao-san')
});
