// Thiết lập gian hàng — one landing page (COMMERCE_LP_PLAN.md).
import {shop} from './shop.mjs';
import {shopSetup, skuTable, marketPdp, marketSearch, orderBoard, chatQueue, listingCompare} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'thiet-lap-gian-hang', channel: 'ecomSetup', name: 'Thiết lập gian hàng', docName: 'Học viện Shopee và Học viện TikTok Shop',
  metaTitle: 'Thiết lập gian hàng trên sàn: hồ sơ, phân quyền, danh mục, SKU, vận chuyển, chính sách',
  metaDescription: 'Mở gian hàng thương mại điện tử bài bản: xác nhận thông tin chủ gian hàng, phân quyền, danh mục và SKU ban đầu, vận chuyển, chính sách bán và trách nhiệm từng người trước khi mở bán.',
  sub: 'Mở bán khi <em>đã sẵn sàng</em>, không vá lỗi sau khi có đơn.',
  lead: 'Doanh nghiệp muốn mở kênh bán nhưng chưa chuẩn bị đủ tài sản và người vận hành. POWAI chuẩn bị thông tin thương hiệu, danh mục, nội dung và các thiết lập cần thiết: xác nhận chủ gian hàng, '
    + 'chuẩn hóa danh mục ban đầu, làm rõ chính sách bán, trách nhiệm và kiểm tra thông tin nhận, bàn giao hàng.',
  cta: 'Xem danh sách thiết lập',
  scene: () => ({main: shopSetup(3), side: marketPdp(),
    calls: [['Hồ sơ & phân quyền', 'Ai sở hữu, ai thao tác'], ['Danh mục & SKU ban đầu', 'Đủ để mở bán'], ['Vận chuyển & chính sách', 'Trước đơn đầu tiên']]}),
  intro: {q: 'Thiết lập gian hàng gồm những gì?',
    a: 'Là toàn bộ việc cần làm trước khi gian hàng nhận đơn đầu tiên trên một sàn cụ thể: đăng ký và xác minh người bán, tài khoản và phân quyền, thông tin shop, danh mục và sản phẩm đầu tiên, '
      + 'kho lấy hàng và vận chuyển, chính sách đổi trả, tin nhắn tự động. Điều kiện và thủ tục khác nhau theo từng sàn, nên chốt sàn trước.',
    facts: [['Làm trên', 'Kênh Người Bán của sàn được chọn'], ['Trước khi', 'Nhận đơn đầu tiên'], ['Xong khi', 'Đơn mẫu đi đúng đầu cuối']]},
  essentials: {title: 'Sáu thứ phải xong trước khi mở bán.', lead: 'Mỗi sàn có hướng dẫn riêng; đây là những phần sàn nào cũng cần.',
    cards: [['store', 'Đăng ký người bán', 'Theo hướng dẫn đăng ký của sàn: cá nhân hoặc doanh nghiệp, giấy tờ, xác minh.'],
      ['users', 'Tài khoản & phân quyền', 'Chủ gian hàng giữ tài khoản chính; nhân sự dùng quyền theo vai trò.'],
      ['layers', 'Danh mục & sản phẩm đầu tiên', 'Nhóm sản phẩm theo cách khách tìm; mỗi biến thể một SKU.'],
      ['box', 'Kho & vận chuyển', 'Địa chỉ lấy hàng, đơn vị vận chuyển, quy cách đóng gói.'],
      ['file', 'Chính sách bán', 'Đổi trả, bảo hành, thời gian xử lý đơn; theo quy định của sàn.'],
      ['chat', 'Tin nhắn & người trực', 'Tin nhắn tự động, câu trả lời mẫu, ca trực.']],
    get: ['POWAI bàn giao', ['Checklist thiết lập theo sàn đã chọn', 'Danh mục và SKU ban đầu', 'Bảng phân quyền', 'Chính sách bán đã duyệt', 'Biên bản thử đơn mẫu']],
    not: ['Tính riêng hoặc cần phối hợp', ['Phí, cọc, điều kiện của sàn', 'Giấy phép ngành hàng đặc thù', 'Nhập toàn bộ sản phẩm (tính theo số SKU)']],
    src: ['shopeeStart', 'ttRegister', 'shopeeCategory']},
  when: {title: 'Khi chuẩn bị mở gian hàng mới trên sàn.', lead: 'Hợp với doanh nghiệp lần đầu bán trên sàn, hoặc mở thêm sàn mới.',
    journey: [['store', 'Chọn sàn'], ['file', 'Đăng ký, xác minh'], ['layers', 'Dựng danh mục'], ['box', 'Thiết lập giao hàng'], ['check', 'Thử đơn mẫu, mở bán']],
    inputs: [['file', 'Giấy tờ doanh nghiệp'], ['table', 'Danh sách sản phẩm'], ['image', 'Ảnh, logo được phép dùng'], ['users', 'Người vận hành']],
    core: 'Chuẩn bị, thiết lập, thử',
    outputs: [['store', 'Gian hàng sẵn sàng'], ['table', 'SKU ban đầu'], ['check', 'Đơn mẫu đi đúng']],
    fit: ['Lần đầu bán trên sàn', 'Mở thêm sàn mới', 'Gian hàng cũ thiết lập dở dang', 'Chuyển gian hàng từ cá nhân sang doanh nghiệp'],
    notFit: ['Chưa chốt sản phẩm, nguồn hàng', 'Sản phẩm không được phép bán trên sàn', 'Không có người vận hành sau mở bán', 'Muốn mở nhiều sàn cùng lúc khi chưa có dữ liệu'],
    src: ['shopeeStart', 'ttRegister']},
  formatsToc: 'Danh sách thiết lập',
  formats: {eyebrow: 'DANH SÁCH THIẾT LẬP', title: 'Năm phần theo thứ tự.', lead: 'Chọn một phần để xem làm gì và kiểm tra gì.',
    whereLabel: 'Làm gì', whatLabel: 'Kiểm tra',
    items: [
      {key: 'setup', label: 'Checklist mở bán', icon: 'check', stage: () => shopSetup(3), tag: 'KÊNH NGƯỜI BÁN', where: 'Mọi mục cần xong trước khi mở bán.', what: 'Mục chặn mở bán hiện rõ, có người phụ trách.',
        more: [['Theo', 'Học viện Shopee: bắt đầu bán hàng; Học viện TikTok Shop: hướng dẫn đăng ký người bán.']]},
      {key: 'sku', label: 'Danh mục & SKU', icon: 'table', stage: () => skuTable(0), tag: 'KÊNH NGƯỜI BÁN', where: 'Sản phẩm đầu tiên, biến thể, tồn.', what: 'Mỗi biến thể một SKU, ảnh riêng, tồn khớp kho.'},
      {key: 'pdp', label: 'Trang sản phẩm đầu tiên', icon: 'tag', stage: () => marketPdp(), tag: 'PHÍA KHÁCH', where: 'Khách thấy gì khi shop mở.', what: 'Ảnh, tên, phân loại, mô tả theo hướng dẫn của sàn.'},
      {key: 'search', label: 'Hiển thị trong tìm kiếm', icon: 'search', stage: () => marketSearch({hot: 0}), tag: 'PHÍA KHÁCH', where: 'Sản phẩm có xuất hiện đúng từ khóa.', what: 'Tên đúng loại sản phẩm, danh mục đúng ngành hàng.'},
      {key: 'chat', label: 'Tin nhắn & người trực', icon: 'chat', stage: () => chatQueue(0), tag: 'PHÍA SHOP', where: 'Ai trả lời khách, trong giờ nào.', what: 'Tin nhắn tự động, câu trả lời mẫu, ca trực.'}
    ],
    src: ['shopeeCategory', 'shopeeImages', 'ttListing']},
  prep: {title: 'Chốt sàn và người vận hành trước.', lead: 'Thủ tục và điều kiện khác nhau theo sàn; không mặc định giống nhau.',
    principle: 'Chọn một sàn để bắt đầu, mở đúng và chạy ổn rồi mới mở thêm.',
    boardLabel: 'CHECKLIST MỞ BÁN', boards: [() => shopSetup(2)],
    tiles: [['file', 'Giấy tờ', 'Theo yêu cầu của sàn'], ['table', 'Danh sách sản phẩm', 'SKU, giá, tồn'], ['image', 'Logo, ảnh', 'Được phép dùng'], ['users', 'Người vận hành', 'Đơn, tin nhắn']],
    assets: [['Giấy tờ', 'Hồ sơ doanh nghiệp', 'Người đại diện.'], ['Dữ liệu', 'Danh sách sản phẩm', 'SKU ban đầu.'], ['Ảnh', 'Logo, ảnh bìa, ảnh sản phẩm', 'Đúng quy định.'], ['Chữ', 'Chính sách bán', 'Doanh nghiệp duyệt.']],
    specs: [['Đăng ký', 'Theo hướng dẫn từng sàn', 'Học viện Shopee: bắt đầu bán hàng; Học viện TikTok Shop: đăng ký người bán.'],
      ['Danh mục', 'Danh mục của shop', 'Sắp sản phẩm theo cách khách tìm.'], ['Ảnh', 'Theo quy định của sàn', 'Kích thước, tỷ lệ, quyền sử dụng.']],
    src: ['shopeeStart', 'ttRegister', 'shopeeImages']},
  goals: {title: 'Thử trước khi khách thật đặt.', lead: 'Nhóm đầu là phía khách, nhóm sau là phía vận hành.',
    items: [
      {key: 'pdp', group: 'Phía khách', groupColor: '#9fd8ff', label: 'Đặt thử một đơn', icon: 'cart', stage: () => marketPdp(), facts: [['Thử', 'Chọn biến thể, đặt, thanh toán.'], ['Kiểm', 'Giá, phí giao, chính sách hiển thị đúng.']]},
      {key: 'compare', group: 'Phía khách', groupColor: '#9fd8ff', label: 'Trang sản phẩm rõ', icon: 'image', stage: () => listingCompare(), facts: [['Cần có', 'Tên đúng loại, ảnh từng mẫu.'], ['Tránh', 'Ảnh chung cho nhiều mẫu.']]},
      {key: 'orders', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Đơn mẫu đi đúng', icon: 'receipt', stage: () => orderBoard(1), stageTag: 'KÊNH NGƯỜI BÁN', facts: [['Thử', 'Xác nhận, đóng gói, bàn giao.'], ['Xong khi', 'Đơn mẫu tới tay người nhận thử.']]},
      {key: 'chat', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Có người trả lời', icon: 'chat', stage: () => chatQueue(2), facts: [['Cần có', 'Ca trực, câu trả lời mẫu.'], ['Tránh', 'Tin nhắn không có người nhận.']]}
    ],
    src: ['shopeeOrders', 'shopeeStart']},
  measure: {title: 'Đo độ sẵn sàng trước khi đo doanh số.', lead: 'Bấm từng tầng. Số là một gian hàng giả định để minh họa cách đọc.', sample: 'Một gian hàng giả định, chỉ để minh họa cách đọc.',
    tiers: [['setup', 'Thiết lập', '6', [['Mục thiết lập', '6', 'Theo checklist.'], ['Còn chặn mở bán', '1', 'Vận chuyển.']]],
      ['sku', 'Sản phẩm', '30', [['SKU dự kiến', '30', 'Đợt đầu.'], ['Đã đăng đúng', '24', 'Ảnh, phân loại, mô tả.']]],
      ['orders', 'Đơn mẫu', '3', [['Đơn mẫu', '3', 'Đi đúng đầu cuối.'], ['Lỗi phát hiện', '2', 'Đã sửa trước mở bán.']]]],
    tips: {sku: 'Nhiều SKU chưa đạt: ưu tiên sản phẩm bán chạy, mở bán dần.', orders: 'Đơn mẫu lỗi: sửa trước khi mở cho khách thật.'},
    note: {label: 'MỞ BÁN DẦN', ic: 'flag', text: 'Mở với nhóm sản phẩm chủ lực trước, thêm dần khi vận hành đã ổn.'},
    src: ['shopeeStart']},
  step2: 'Thông tin shop, danh mục, sản phẩm đầu tiên, vận chuyển, chính sách, tin nhắn tự động.',
  rollout: {title: 'Năm bước từ chọn sàn tới mở bán.',
    checks: ['Chốt sàn triển khai', 'Hồ sơ người bán đã duyệt', 'Phân quyền theo vai trò', 'SKU ban đầu đúng biến thể',
      'Kho lấy hàng, vận chuyển', 'Chính sách bán đã duyệt', 'Tin nhắn tự động, ca trực', 'Đơn mẫu đi đúng đầu cuối'],
    src: ['shopeeStart', 'ttRegister']},
  faq: [['Mở gian hàng mất bao lâu?', 'Tùy thời gian xét duyệt của sàn và độ sẵn sàng của hồ sơ, sản phẩm; lịch chốt sau khi chọn sàn.'],
    ['Nên mở sàn nào trước?', 'Sàn nơi khách của bạn đang mua nhiều nhất; mở một sàn cho ổn rồi mới mở thêm.'],
    ['Có mở gian hàng chính hãng được không?', 'Điều kiện gian hàng chính hãng theo quy định từng sàn; POWAI chuẩn bị hồ sơ theo hướng dẫn.'],
    ['Sau khi mở ai vận hành?', 'Đội doanh nghiệp hoặc POWAI theo phạm vi Vận hành gian hàng.']],
  faqSrc: ['shopeeEdu', 'ttUni'],
  recap: {title: 'Ba việc trước ngày mở bán.', items: [['Checklist xong', 'Không còn mục chặn.', '#dinh-dang', 'check'],
    ['SKU đúng', 'Mỗi biến thể một mã.', '#dinh-dang', 'table'], ['Đơn mẫu đi đúng', 'Đầu cuối.', '#muc-tieu', 'receipt']]},
  sisters: sisters('shopee', 'tiktok-shop', 'toi-uu-san-pham')
});
