// TikTok Shop — one landing page (COMMERCE_LP_PLAN.md). Facts from Học viện TikTok Shop.
import {shop} from './shop.mjs';
import {videoShop, marketPdp, skuTable, orderBoard, storyboard, chatQueue, reasons, listingCompare, netRevenue} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'tiktok-shop', channel: 'ecomTiktok', name: 'TikTok Shop', docName: 'Học viện TikTok Shop',
  metaTitle: 'Dịch vụ TikTok Shop: video gắn sản phẩm, trang sản phẩm, danh mục SKU, xử lý đơn',
  metaDescription: 'Kết nối nội dung TikTok với danh mục sản phẩm và gian hàng: video gắn đúng sản phẩm, trang sản phẩm khớp video, biến thể và giá đúng, theo dõi đơn và phản hồi sau nội dung.',
  sub: 'Sản phẩm trong video, trang sản phẩm và biến thể mua <em>phải khớp nhau</em>.',
  lead: 'Video có người xem nhưng sản phẩm được gắn chưa khớp và khách khó đi đến mua. POWAI nối nội dung với danh mục: chọn cảnh demo đúng sản phẩm, đối chiếu sản phẩm được gắn, '
    + 'rà giá, biến thể, thông tin mua và theo dõi đơn, phản hồi sau mỗi nội dung.',
  cta: 'Xem luồng video → đơn',
  scene: () => ({main: orderBoard(0), side: videoShop(),
    calls: [['Video gắn đúng sản phẩm', 'Cảnh demo = sản phẩm bán'], ['Trang sản phẩm khớp video', 'Giá, biến thể, thông tin'], ['Đơn sau nội dung', 'Xử lý kịp khi video lên']]}),
  intro: {q: 'Dịch vụ TikTok Shop gồm gì?',
    a: 'TikTok Shop là nơi khách mua ngay trong ứng dụng TikTok, từ video, trang cửa hàng hoặc tìm kiếm. Dịch vụ gồm thiết lập và chuẩn hóa sản phẩm trong Trung tâm người bán, '
      + 'nối video với đúng sản phẩm, rà trang sản phẩm theo quy định đăng bán và vận hành đơn phát sinh sau mỗi nội dung.',
    facts: [['Khách mua từ', 'Video, trang cửa hàng, tìm kiếm'], ['Trọng tâm', 'Video ↔ sản phẩm ↔ đơn'], ['Đo bằng', 'Đơn hoàn tất theo nội dung']]},
  essentials: {title: 'Sáu điều quyết định TikTok Shop bán được.', lead: 'Theo Học viện TikTok Shop và kinh nghiệm vận hành.',
    cards: [['store', 'Đăng ký & thương hiệu', 'Hồ sơ người bán theo hướng dẫn đăng ký; sản phẩm có thương hiệu cần chứng nhận phù hợp.'],
      ['tag', 'Đăng bán đúng nguyên tắc', 'Tiêu đề đầy đủ, chính xác, ngắn gọn; mô tả, hình ảnh, video đúng sản phẩm; giá theo nguyên tắc đăng bán giá.'],
      ['video', 'Video gắn đúng sản phẩm', 'Cảnh demo, sản phẩm được gắn và trang chi tiết nói cùng một thứ.'],
      ['shield', 'Chính sách nội dung', 'Không phóng đại công dụng, không dùng nội dung không được phép.'],
      ['receipt', 'Đơn tăng theo video', 'Một video tốt có thể làm đơn tăng nhanh; tồn kho và người xử lý phải sẵn sàng.'],
      ['chart', 'Đọc theo nội dung', 'Đơn và hoàn hủy theo từng video để biết nội dung nào bán được.']],
    get: ['POWAI bàn giao', ['Danh mục SKU chuẩn hóa', 'Trang sản phẩm theo nguyên tắc đăng bán', 'Danh sách video ↔ sản phẩm gắn', 'Quy trình đơn khi video tăng', 'Báo cáo theo nội dung']],
    not: ['Tính riêng hoặc cần phối hợp', ['Quay dựng video, người sáng tạo nội dung', 'Phí sàn, chương trình, quảng cáo', 'Kho và vận chuyển thực tế']],
    src: ['ttRegister', 'ttTitle', 'ttContent', 'ttBrand']},
  when: {title: 'Khi video có người xem mà đơn không tương xứng.', lead: 'Hợp với thương hiệu bán hàng tiêu dùng, có nội dung video hoặc hợp tác nhà sáng tạo.',
    journey: [['video', 'Khách xem video'], ['tag', 'Bấm sản phẩm được gắn'], ['list', 'Chọn biến thể'], ['cart', 'Đặt hàng trong ứng dụng'], ['box', 'Shop xử lý, giao']],
    inputs: [['video', 'Video, nội dung sẵn có'], ['table', 'Bảng SKU, giá, tồn'], ['users', 'Người xử lý đơn'], ['store', 'Quyền Trung tâm người bán']],
    core: 'Nối nội dung với danh mục và đơn',
    outputs: [['tag', 'Sản phẩm gắn đúng'], ['receipt', 'Đơn xử lý kịp'], ['chart', 'Báo cáo theo nội dung']],
    fit: ['Video nhiều người xem mà ít đơn', 'Khách hỏi giá, hỏi mẫu dù đã có trong video', 'Đơn dồn dập sau một video, xử lý không kịp', 'Hợp tác nhà sáng tạo cần sản phẩm rõ'],
    notFit: ['Chưa có sản phẩm được phép bán trên sàn', 'Sản phẩm thương hiệu chưa có giấy tờ phù hợp', 'Không có người xử lý đơn', 'Muốn nội dung phóng đại công dụng'],
    src: ['ttUni', 'ttListing']},
  formatsToc: 'Luồng video → đơn',
  formats: {eyebrow: 'LUỒNG VIDEO → ĐƠN', title: 'Năm điểm phải khớp nhau.', lead: 'Chọn một điểm để xem kiểm tra gì.',
    whereLabel: 'Kiểm tra', whatLabel: 'Sửa thế nào',
    items: [
      {key: 'video', label: 'Video gắn sản phẩm', icon: 'video', stage: () => videoShop(), tag: 'PHÍA KHÁCH',
        where: 'Sản phẩm trong video có đúng sản phẩm được gắn không.', what: 'Cảnh demo đúng mẫu, tên và giá trên thẻ sản phẩm khớp trang chi tiết.'},
      {key: 'story', label: 'Kịch bản bán hàng', icon: 'list', stage: () => storyboard(1), tag: 'BÀI MẪU',
        where: 'Video có dẫn tới mua không.', what: 'Mở đầu đúng nhu cầu, demo, bằng chứng, kết bằng hành động bấm sản phẩm.'},
      {key: 'pdp', label: 'Trang sản phẩm', icon: 'tag', stage: () => marketPdp(), tag: 'PHÍA KHÁCH',
        where: 'Tiêu đề, mô tả, hình ảnh, biến thể.', what: 'Tiêu đề đầy đủ, chính xác, ngắn gọn; ảnh và video đúng sản phẩm.',
        more: [['Theo', 'Học viện TikTok Shop: tiêu đề, mô tả, hình ảnh và video về sản phẩm.']]},
      {key: 'sku', label: 'Danh mục SKU', icon: 'table', stage: () => skuTable(1), tag: 'TRUNG TÂM NGƯỜI BÁN',
        where: 'Biến thể, giá, tồn kho.', what: 'Dùng chung bảng SKU với các kênh khác để tồn kho không lệch.'},
      {key: 'orders', label: 'Đơn sau video', icon: 'receipt', stage: () => orderBoard(0), tag: 'TRUNG TÂM NGƯỜI BÁN',
        where: 'Đơn tăng sau khi video lên.', what: 'Người xử lý sẵn sàng, đơn thiếu hàng có cách xử lý.'}
    ],
    src: ['ttTitle', 'ttListing', 'ttContent']},
  prep: {title: 'Sản phẩm sẵn sàng trước khi video lên.', lead: 'Video tốt mà sản phẩm chưa sẵn sàng là mất khách ngay lúc đông nhất.',
    principle: 'Không gắn sản phẩm vào video khi tồn kho, giá, biến thể chưa kiểm tra.',
    boardLabel: 'KỊCH BẢN VIDEO', boards: [() => storyboard(0)],
    tiles: [['table', 'Bảng SKU', 'Giá, tồn, biến thể'], ['video', 'Video, cảnh quay', 'Được phép dùng'], ['file', 'Giấy tờ thương hiệu', 'Nếu có'], ['users', 'Người xử lý đơn', 'Khi video lên']],
    assets: [['Dữ liệu', 'Bảng SKU', 'Khớp kho.'], ['Video', 'Nội dung sẵn có', 'Quyền nhạc, hình.'], ['Giấy tờ', 'Chứng nhận thương hiệu', 'Với hàng có thương hiệu.'], ['Hệ thống', 'Trung tâm người bán', 'Phân quyền.']],
    specs: [['Đăng ký', 'Theo hướng dẫn đăng ký người bán', 'Điều kiện cá nhân và doanh nghiệp trong Học viện TikTok Shop.'],
      ['Thương hiệu', 'Chứng nhận thương hiệu', 'Sản phẩm có thương hiệu cần đủ ủy quyền, chứng nhận.'],
      ['Nội dung', 'Chính sách nội dung TikTok Shop', 'Nội dung quảng bá sản phẩm phải chân thực.']],
    src: ['ttRegister', 'ttBrand', 'ttContent']},
  goals: {title: 'Thử những lúc video và đơn không khớp.', lead: 'Nhóm đầu là phía khách, nhóm sau là phía vận hành.',
    items: [
      {key: 'mismatch', group: 'Phía khách', groupColor: '#f5a3c0', label: 'Video một đằng, trang một nẻo', icon: 'alert', stage: () => listingCompare(),
        facts: [['Nguyên nhân', 'Gắn nhầm sản phẩm hoặc ảnh không đúng mẫu.'], ['Sửa', 'Đối chiếu từng video với sản phẩm gắn.']]},
      {key: 'out', group: 'Phía khách', groupColor: '#f5a3c0', label: 'Hết mẫu trong video', icon: 'tag', stage: () => marketPdp({state: 'out'}),
        facts: [['Cần có', 'Tồn kho cập nhật trước khi video lên.'], ['Thử', 'Chọn mẫu hết, xem thông báo.']]},
      {key: 'surge', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Đơn dồn sau video', icon: 'receipt', stage: () => orderBoard(0), stageTag: 'TRUNG TÂM NGƯỜI BÁN',
        facts: [['Cần có', 'Người trực, quy trình đóng gói theo lô.'], ['Tránh', 'Trễ hạn xử lý ảnh hưởng gian hàng.']]},
      {key: 'chat', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Câu hỏi sau video', icon: 'chat', stage: () => chatQueue(0),
        facts: [['Cần có', 'Câu trả lời mẫu cho câu hỏi về video.'], ['Đọc', 'Câu hỏi lặp lại: sửa video hoặc trang.']]},
      {key: 'money', group: 'Phía vận hành', groupColor: '#88e4ff', label: 'Tiền thực nhận', icon: 'wallet', stage: () => netRevenue(),
        facts: [['Đọc', 'Trừ phí, hoa hồng liên kết, mã giảm giá, hoàn hủy.'], ['Vì sao', 'Doanh số video không phải lợi nhuận.']]}
    ],
    src: ['ttListing', 'ttContent']},
  measure: {title: 'Đọc theo từng nội dung.', lead: 'Bấm từng tầng. Số là một video giả định để minh họa cách đọc.', sample: 'Một video giả định, chỉ để minh họa cách đọc.',
    tiers: [['view', 'Lượt xem', '50.000', [['Lượt xem video', '50.000', 'Trong 7 ngày.'], ['Bấm sản phẩm', '1.900', 'Từ thẻ gắn.']]],
      ['order', 'Đơn đặt', '310', [['Đơn đặt', '310', 'Từ video.'], ['Hủy trước giao', '26', 'Theo lý do.']]],
      ['done', 'Hoàn tất', '262', [['Đơn hoàn tất', '262', 'Sau giao, hoàn.'], ['Hoàn hàng', '12', 'Sai mẫu, đổi ý.']]]],
    tips: {view: 'Nhiều lượt xem, ít bấm sản phẩm: video chưa dẫn tới sản phẩm, hoặc gắn chưa đúng.', order: 'Hủy nhiều: kiểm tra tồn và thời gian xử lý.'},
    note: {label: 'LƯỢT XEM KHÁC ĐƠN', ic: 'chart', text: 'Đọc đơn hoàn tất theo từng video; video nhiều lượt xem chưa chắc bán được.'},
    src: ['ttUni']},
  step2: 'Tiêu đề, mô tả, ảnh, video, giá, biến thể theo nguyên tắc đăng bán của TikTok Shop.',
  rollout: {title: 'Năm bước từ danh mục tới video bán được.',
    checks: ['Hồ sơ người bán đã duyệt', 'Giấy tờ thương hiệu (nếu có)', 'Tiêu đề, ảnh theo nguyên tắc', 'Bảng SKU khớp kho',
      'Video gắn đúng sản phẩm', 'Người trực khi video lên', 'Câu trả lời mẫu', 'Báo cáo đơn theo video'],
    src: ['ttListing', 'ttRegister']},
  faq: [['Có làm video cho TikTok Shop không?', 'Có thể tách phạm vi riêng; trang này tập trung vào gian hàng, sản phẩm và vận hành.'],
    ['Có hợp tác nhà sáng tạo (affiliate) không?', 'Có thể hỗ trợ chuẩn bị sản phẩm và thông tin; điều kiện tham gia theo hướng dẫn của TikTok Shop.'],
    ['Bán hàng có thương hiệu cần gì?', 'Chứng nhận hoặc ủy quyền thương hiệu theo nguyên tắc đăng bán sản phẩm có thương hiệu.'],
    ['Có cam kết doanh số không?', 'Không. Doanh số phụ thuộc sản phẩm, nội dung và giá; POWAI sửa những gì cản khách mua.']],
  faqSrc: ['ttUni', 'ttBrand'],
  recap: {title: 'Ba việc cho TikTok Shop.', items: [['Video gắn đúng', 'Cảnh demo = sản phẩm bán.', '#dinh-dang', 'video'],
    ['Trang sản phẩm đúng nguyên tắc', 'Tiêu đề, ảnh, giá.', '#dinh-dang', 'tag'], ['Đơn có người nhận', 'Khi video lên.', '#muc-tieu', 'receipt']]},
  sisters: sisters('content-thuong-mai-dien-tu', 'shopee', 'van-hanh-gian-hang')
});
