// Vận hành gian hàng — one landing page (COMMERCE_LP_PLAN.md).
import {shop} from './shop.mjs';
import {orderBoard, chatQueue, reasons, skuTable, netRevenue, marketPdp, shopSetup} from './mocks.mjs';
import {CHECKED, sisters} from './sources.mjs';
export {CHECKED};

export default shop({
  slug: 'van-hanh-gian-hang', channel: 'ecomOps', name: 'Vận hành gian hàng', docName: 'Học viện Shopee và Học viện TikTok Shop',
  metaTitle: 'Vận hành gian hàng thương mại điện tử: đơn hàng, tin nhắn, tồn kho, hoàn hủy, đối soát',
  metaDescription: 'Phân định trách nhiệm cập nhật hàng hóa, xử lý đơn, trả lời khách và theo dõi hoàn hủy trên các sàn; mỗi đơn có trạng thái, người xử lý và cách chuyển tiếp khi thiếu hàng.',
  sub: 'Mỗi đơn có <em>trạng thái</em>, <em>người xử lý</em> và cách xử lý khi thiếu hàng.',
  lead: 'Đơn và tin nhắn bị bỏ sót khi nhiều người cùng phụ trách là vấn đề hay gặp. POWAI phân loại đơn mới, giao người xác nhận tình trạng, đối chiếu đóng gói với SKU, '
    + 'ghi nhận bàn giao và ngoại lệ, trả lời khách theo ca và đối soát hoàn hủy, tiền thực nhận hằng tháng.',
  cta: 'Xem bảng vận hành',
  scene: () => ({main: orderBoard(1), side: chatQueue(2),
    calls: [['Phân loại đơn', 'Chờ, đóng gói, bàn giao'], ['Người phụ trách', 'Đơn và tin nhắn'], ['Hoàn, hủy theo lý do', 'Sửa lỗi của shop trước']]}),
  intro: {q: 'Vận hành gian hàng là gì?',
    a: 'Là công việc hằng ngày sau khi gian hàng đã mở: cập nhật tồn kho, xác nhận và đóng gói đơn đúng hạn, bàn giao vận chuyển, trả lời tin nhắn, xử lý hoàn trả và theo dõi các chỉ số '
      + 'sàn dùng để đánh giá shop như tỷ lệ đơn không thành công. Làm tốt thì đơn đi đúng và shop giữ được uy tín trên sàn.',
    facts: [['Hằng ngày', 'Đơn, tồn kho, tin nhắn'], ['Hằng tháng', 'Hoàn hủy, đối soát tiền'], ['Sàn đánh giá', 'Tỷ lệ đơn không thành công, hạn xử lý']]},
  essentials: {title: 'Sáu việc giữ gian hàng chạy ổn.', lead: 'Theo hướng dẫn xử lý đơn trong Học viện Shopee và kinh nghiệm vận hành.',
    cards: [['receipt', 'Xử lý đơn đúng hạn', 'Xác nhận, đóng gói, bàn giao trong thời hạn tiêu chuẩn của sàn.'],
      ['table', 'Tồn kho đúng', 'Cập nhật tồn một nơi; hết ở kho là hết trên mọi kênh.'],
      ['users', 'Người phụ trách rõ', 'Mỗi bước có người nhận; ca trực đơn và tin nhắn.'],
      ['chat', 'Trả lời khách', 'Câu trả lời mẫu, chuyển người phụ trách khi khiếu nại.'],
      ['alert', 'Đơn không thành công', 'Theo dõi tỷ lệ đơn không thành công; tách lỗi shop với khách đổi ý.'],
      ['wallet', 'Đối soát tiền', 'Tiền thực nhận sau phí, mã giảm giá, hoàn hủy; khớp với giá vốn.']],
    get: ['POWAI bàn giao', ['Bảng phân công đơn và tin nhắn', 'Quy trình xử lý thiếu hàng, đổi trả', 'Câu trả lời mẫu', 'Báo cáo hoàn hủy theo lý do', 'Đối soát tiền thực nhận hằng tháng']],
    not: ['Tính riêng hoặc cần phối hợp', ['Kho, đóng gói, vận chuyển thực tế', 'Trực tin nhắn ngoài khung giờ đã thống nhất', 'Phí sàn, chương trình']],
    src: ['shopeeOrders', 'shopeeFailRate', 'shopeeFees']},
  when: {title: 'Khi đã có đơn nhưng vận hành rối.', lead: 'Hợp với gian hàng có đơn đều, nhiều người cùng thao tác, bán trên nhiều sàn.',
    journey: [['receipt', 'Đơn mới vào'], ['users', 'Giao người xác nhận'], ['box', 'Đóng gói theo SKU'], ['route', 'Bàn giao vận chuyển'], ['chart', 'Đối soát, hoàn hủy']],
    inputs: [['store', 'Quyền Kênh Người Bán'], ['table', 'Bảng SKU, tồn kho'], ['users', 'Danh sách người vận hành'], ['box', 'Quy trình kho hiện tại']],
    core: 'Phân công, quy trình, đối soát',
    outputs: [['users', 'Bảng phân công'], ['receipt', 'Quy trình đơn'], ['chart', 'Báo cáo tháng']],
    fit: ['Đơn hoặc tin nhắn bị bỏ sót', 'Hay thiếu hàng khi đóng gói', 'Tỷ lệ đơn không thành công tăng', 'Không biết tiền thực nhận mỗi tháng'],
    notFit: ['Chưa có đơn đều', 'Không cho truy cập Kênh Người Bán', 'Muốn giấu lỗi để giữ chỉ số', 'Không có kho, người đóng gói'],
    src: ['shopeeOrders', 'shopeeFailRate']},
  formatsToc: 'Bảng vận hành',
  formats: {eyebrow: 'BẢNG VẬN HÀNH', title: 'Năm màn hình người vận hành xem mỗi ngày.', lead: 'Chọn một màn hình để xem làm gì ở đó.',
    whereLabel: 'Dùng để', whatLabel: 'Quy tắc',
    items: [
      {key: 'orders', label: 'Bảng đơn', icon: 'receipt', stage: () => orderBoard(1), tag: 'KÊNH NGƯỜI BÁN', where: 'Đơn theo trạng thái.', what: 'Đơn chờ quá lâu nổi lên; mỗi cột có người phụ trách.',
        more: [['Theo', 'Thời hạn xử lý đơn tiêu chuẩn trong Học viện Shopee.']]},
      {key: 'sku', label: 'Tồn kho', icon: 'table', stage: () => skuTable(2), tag: 'KÊNH NGƯỜI BÁN', where: 'Tồn theo SKU, mọi kênh.', what: 'Hết ở kho cập nhật ngay; không bán âm.'},
      {key: 'chat', label: 'Tin nhắn', icon: 'chat', stage: () => chatQueue(2), tag: 'PHÍA SHOP', where: 'Câu hỏi trước và sau mua.', what: 'Tin chưa có người nhận nổi lên đầu; khiếu nại chuyển trưởng ca.'},
      {key: 'reasons', label: 'Hoàn, hủy', icon: 'chart', stage: () => reasons(1), tag: 'SỐ MẪU', where: 'Lý do hoàn, hủy.', what: 'Lỗi của shop (thiếu hàng, sai mẫu) sửa trước.'},
      {key: 'money', label: 'Đối soát tiền', icon: 'wallet', stage: () => netRevenue(), where: 'Tiền thực nhận.', what: 'Đối chiếu với giá vốn mỗi tháng.'}
    ],
    src: ['shopeeOrders', 'shopeeFailRate', 'shopeeFees']},
  prep: {title: 'Ai làm gì, trong giờ nào.', lead: 'Vận hành rối thường vì không ai chịu trách nhiệm rõ ràng.',
    principle: 'Mỗi bước của đơn có một người chịu trách nhiệm và một người thay thế.',
    boardLabel: 'BẢNG ĐƠN', boards: [() => orderBoard(0)],
    tiles: [['users', 'Danh sách người vận hành', 'Ca, vai trò'], ['table', 'Bảng SKU', 'Tồn kho thật'], ['box', 'Quy trình kho', 'Đóng gói, bàn giao'], ['chat', 'Câu hỏi hay gặp', 'Để viết câu trả lời mẫu']],
    assets: [['Người', 'Vai trò, ca trực', 'Người thay thế.'], ['Dữ liệu', 'Bảng SKU', 'Tồn thật.'], ['Quy trình', 'Kho, đóng gói', 'Hiện tại.'], ['Chữ', 'Câu trả lời mẫu', 'Doanh nghiệp duyệt.']],
    specs: [['Hạn xử lý đơn', 'Theo tiêu chuẩn của sàn', 'Xem trong Học viện Shopee.'], ['Đơn không thành công', 'Cách tính theo sàn', 'Ảnh hưởng tới đánh giá shop.'], ['Phí', 'Các loại phí bán hàng', 'Dùng khi đối soát tiền.']],
    src: ['shopeeOrders', 'shopeeFailRate', 'shopeeFees']},
  goals: {title: 'Những lúc vận hành dễ sai.', lead: 'Nhóm đầu là phía khách, nhóm sau là phía shop.',
    items: [
      {key: 'out', group: 'Phía khách', groupColor: '#9fe0c9', label: 'Khách đặt mẫu vừa hết', icon: 'tag', stage: () => marketPdp({state: 'out'}), facts: [['Xử lý', 'Liên hệ khách, đổi mẫu hoặc hủy theo quy định.'], ['Phòng', 'Cập nhật tồn ngay khi hết.']]},
      {key: 'chat', group: 'Phía khách', groupColor: '#9fe0c9', label: 'Tin nhắn không ai trả lời', icon: 'chat', stage: () => chatQueue(2), facts: [['Cần có', 'Ca trực, tin chưa giao nổi lên đầu.'], ['Đọc', 'Thời gian phản hồi theo ca.']]},
      {key: 'short', group: 'Phía shop', groupColor: '#88e4ff', label: 'Thiếu hàng khi đóng gói', icon: 'box', stage: () => orderBoard(1), stageTag: 'KÊNH NGƯỜI BÁN', facts: [['Nguyên nhân', 'Tồn trên sàn khác kho.'], ['Sửa', 'Một bảng SKU, cập nhật một nơi.']]},
      {key: 'setup', group: 'Phía shop', groupColor: '#88e4ff', label: 'Thiết lập còn thiếu', icon: 'gear', stage: () => shopSetup(3), stageTag: 'KÊNH NGƯỜI BÁN', facts: [['Kiểm', 'Tin nhắn tự động, chính sách, kho lấy hàng.'], ['Vì sao', 'Thiếu thiết lập gây lỗi lặp lại.']]},
      {key: 'money', group: 'Phía shop', groupColor: '#88e4ff', label: 'Tiền không khớp', icon: 'wallet', stage: () => netRevenue(), facts: [['Đối soát', 'Phí, mã giảm giá, hoàn hủy.'], ['Tần suất', 'Hằng tháng.']]}
    ],
    src: ['shopeeOrders', 'shopeeFees']},
  measure: {title: 'Đo vận hành bằng đơn đi đúng.', lead: 'Bấm từng tầng. Số là một tháng giả định để minh họa cách đọc.',
    tiers: [['in', 'Đơn vào', '900', [['Đơn mới', '900', 'Mọi sàn.'], ['Xác nhận trễ hạn', '14', 'Theo ca.']]],
      ['ship', 'Bàn giao', '860', [['Bàn giao vận chuyển', '860', 'Đúng hạn.'], ['Thiếu hàng', '19', 'Tồn lệch.']]],
      ['done', 'Hoàn tất', '812', [['Đơn hoàn tất', '812', 'Sau giao, hoàn.'], ['Không thành công', '48', 'Theo lý do.']]]],
    tips: {in: 'Trễ xác nhận tập trung một ca: xem lại phân công.', ship: 'Thiếu hàng: kiểm quy tắc cập nhật tồn kho.'},
    note: {label: 'TÁCH LỖI SHOP VÀ LỖI KHÁCH', ic: 'alert', text: 'Thiếu hàng, sai mẫu, trễ hạn là lỗi của shop; khách đổi ý, không nhận hàng xử lý khác. Sửa lỗi của shop trước.'},
    src: ['shopeeFailRate', 'shopeeOrders']},
  step2: 'Phân công theo ca, quy trình đơn, câu trả lời mẫu, quy tắc cập nhật tồn.',
  rollout: {title: 'Năm bước từ rà soát tới vận hành ổn định.',
    checks: ['Mỗi bước đơn có người phụ trách', 'Có người thay thế theo ca', 'Tồn kho cập nhật một nơi', 'Quy trình thiếu hàng',
      'Câu trả lời mẫu đã duyệt', 'Theo dõi tỷ lệ đơn không thành công', 'Báo cáo hoàn hủy theo lý do', 'Đối soát tiền hằng tháng'],
    src: ['shopeeOrders', 'shopeeFailRate']},
  faq: [['POWAI có trực đơn thay doanh nghiệp không?', 'Có thể theo phạm vi và khung giờ thống nhất; kho và đóng gói vẫn do doanh nghiệp.'],
    ['Vận hành nhiều sàn cùng lúc được không?', 'Được; nên dùng chung bảng SKU và một bảng đơn tổng để không lệch.'],
    ['Có dùng phần mềm quản lý bán hàng không?', 'Nếu doanh nghiệp đang dùng, POWAI làm trên phần mềm đó; kết nối mới xem Tích hợp hệ thống.'],
    ['Báo cáo gửi khi nào?', 'Hằng tuần cho đơn và tin nhắn; hằng tháng cho hoàn hủy và đối soát tiền.']],
  faqSrc: ['shopeeOrders', 'shopeeEdu'],
  recap: {title: 'Ba việc cho vận hành ổn.', items: [['Người phụ trách rõ', 'Mỗi bước đơn.', '#chuan-bi', 'users'],
    ['Tồn kho đúng', 'Cập nhật một nơi.', '#dinh-dang', 'table'], ['Đối soát hằng tháng', 'Hoàn hủy, tiền.', '#do-luong', 'wallet']]},
  sisters: sisters('shopee', 'tiktok-shop', 'website-ban-hang')
});
